---
- name: Clear cache and enable swap
  hosts: all
  become: true

  tasks:
    - name: Clear Page Cache
      ansible.builtin.shell:
        cmd: sync && echo 1 > /proc/sys/vm/drop_caches

    - name: Create Swap File
      ansible.builtin.command:
        cmd: fallocate -l 1G /swapfile
        creates: /swapfile
      become: true

    - name: Set Permissions for Swap File
      ansible.builtin.file:
        path: /swapfile
        mode: '0600'
        owner: root
        group: root

    - name: Format Swap File
      ansible.builtin.shell:
        cmd: mkswap /swapfile

    - name: Enable Swap File
      ansible.builtin.shell:
        cmd: swapon /swapfile

    - name: Set Job ID number
      set_stats:
        data:
          ac_job_id: "{{ awx_job_id }}"