---
- name: Disable and remove swap file
  hosts: all
  become: true

  tasks:


    - name: Find and kill all mem_test.py processes
      ansible.builtin.shell:
        cmd: "pkill -f 'python.*mem_test.py'"
      ignore_errors: true  # Ignore erros caso nenhum processo seja encontrado

    - name: Confirm processes are terminated
      ansible.builtin.shell:
        cmd: "pgrep -f 'python.*mem_test.py'"
      register: pgrep_output
      failed_when: pgrep_output.stdout != ""
      ignore_errors: true

    - debug:
        msg: "All instances of mem_test.py have been terminated."

    - name: Clearing leftover in-memory swap data
      ansible.builtin.shell:
        cmd: echo 3 > /proc/sys/vm/drop_caches

    - name: Disable Swap File
      ansible.builtin.shell:
        cmd: swapoff /swapfile

    - name: Remove Swap File
      ansible.builtin.file:
        path: /swapfile
        state: absent
