---
- name: Configurar parâmetros de kernel
  hosts: all
  become: true
  tasks:
    - name: Desabilitar swap
      sysctl:
        name: vm.swappiness
        value: 10
        state: present
        sysctl_set: yes
        reload: yes

    - name: Habilitar IP forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: 1
        state: present
        sysctl_set: yes
        reload: yes
