# playbooks/config/install_node_exporter.yml
---
- name: Instalar e iniciar node_exporter em hosts Linux
  hosts: LINUX
  become: true

  vars:
    node_exporter_version: "1.8.1"
    node_exporter_user: "nodeusr"
    node_exporter_port: 9100

  tasks:
    - name: Criar usuário para o node_exporter
      ansible.builtin.user:
        name: "{{ node_exporter_user }}"
        shell: /sbin/nologin
        system: true

    - name: Detectar arquitetura do host
      set_fact:
        arch_suffix: >-
          {{ 'amd64' if ansible_architecture in ['x86_64'] else
             'arm64' if ansible_architecture in ['aarch64'] else
             'unsupported' }}

    - name: Falhar se arquitetura não suportada
      fail:
        msg: "Arquitetura {{ ansible_architecture }} não suportada para node_exporter"
      when: arch_suffix == 'unsupported'

    - name: Baixar binário do node_exporter
      ansible.builtin.get_url:
        url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-{{ arch_suffix }}.tar.gz"
        dest: "/tmp/node_exporter.tar.gz"
        mode: '0644'

    - name: Criar diretório temporário de extração
      file:
        path: /tmp/node_exporter_extract
        state: directory
        mode: '0755'

    - name: Descompactar binário
      ansible.builtin.unarchive:
        src: "/tmp/node_exporter.tar.gz"
        dest: "/tmp/node_exporter_extract"
        remote_src: yes

    - name: Copiar binário para /usr/local/bin
      ansible.builtin.copy:
        src: "/tmp/node_exporter_extract/node_exporter-{{ node_exporter_version }}.linux-{{ arch_suffix }}/node_exporter"
        dest: "/usr/local/bin/node_exporter"
        mode: '0755'
        remote_src: yes

    - name: Criar unidade systemd
      ansible.builtin.copy:
        dest: /etc/systemd/system/node_exporter.service
        content: |
          [Unit]
          Description=Prometheus Node Exporter
          After=network.target

          [Service]
          User={{ node_exporter_user }}
          Group={{ node_exporter_user }}
          Type=simple
          ExecStart=/usr/local/bin/node_exporter --web.listen-address=:{{ node_exporter_port }}

          [Install]
          WantedBy=multi-user.target
        mode: '0644'

    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Abrir porta no firewalld (se disponível)
      ansible.posix.firewalld:
        port: "{{ node_exporter_port }}/tcp"
        permanent: true
        state: enabled
        immediate: true
      ignore_errors: true

    - name: Ativar e iniciar node_exporter
      ansible.builtin.systemd:
        name: node_exporter
        enabled: true
        state: started
