- name: Instalar e iniciar node_exporter em hosts Linux
  hosts: LINUX
  become: true

  vars:
    node_exporter_version: "1.8.1"
    node_exporter_user: "nodeusr"
    node_exporter_port: 9100
    tmp_dir: "/tmp/node_exporter_extract"

  tasks:

    - name: Definir arquitetura correta para download
      set_fact:
        arch_suffix: >-
          {{ 'amd64' if ansible_architecture in ['x86_64'] else
             'arm64' if ansible_architecture in ['aarch64'] else
             'unsupported' }}

    - name: Falhar se arquitetura não suportada
      fail:
        msg: "Arquitetura '{{ ansible_architecture }}' não suportada para node_exporter"
      when: arch_suffix == 'unsupported'

    - name: Criar usuário para o node_exporter
      ansible.builtin.user:
        name: "{{ node_exporter_user }}"
        shell: /sbin/nologin
        system: true

    - name: Baixar binário do node_exporter
      get_url:
        url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-{{ arch_suffix }}.tar.gz"
        dest: "/tmp/node_exporter.tar.gz"
        mode: '0644'

    - name: Criar diretório temporário de extração
      file:
        path: "{{ tmp_dir }}"
        state: directory

    - name: Descompactar node_exporter
      unarchive:
        src: /tmp/node_exporter.tar.gz
        dest: "{{ tmp_dir }}"
        remote_src: yes

    - name: Obter nome do diretório extraído
      find:
        paths: "{{ tmp_dir }}"
        file_type: directory
        patterns: "node_exporter-*"
      register: extracted_dir

    - name: Definir caminho do binário extraído
      set_fact:
        extracted_bin_path: "{{ extracted_dir.files[0].path }}/node_exporter"

    - name: Copiar binário para /usr/local/bin
      copy:
        src: "{{ extracted_bin_path }}"
        dest: /usr/local/bin/node_exporter
        mode: '0755'
        remote_src: true

    - name: Criar unidade systemd
      copy:
        dest: /etc/systemd/system/node_exporter.service
        content: |
          [Unit]
          Description=Prometheus Node Exporter
          After=network.target

          [Service]
          User={{ node_exporter_user }}
          Group={{ node_exporter_user }}
          Type=simple
          ExecStart=/usr/local/bin/node_exporter --web.listen-address=:{{ node_exporter_port }}

          [Install]
          WantedBy=multi-user.target
        mode: '0644'

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Abrir porta do firewalld
      firewalld:
        port: "{{ node_exporter_port }}/tcp"
        permanent: true
        state: enabled
        immediate: true
      ignore_errors: true

    - name: Iniciar e habilitar node_exporter
      systemd:
        name: node_exporter
        enabled: true
        state: started
