---
- name: Importar configuração de hardening base
  import_playbook: "config_basic_packages.yml"

- name: Configurar serviços essenciais
  import_playbook: "config_basic_services.yml"

- name: Configurar logging do Ansible
  import_playbook: "config_ansible_log.yml"

- name: Configurar motd
  import_playbook: "config_motd.yml"

- name: Configurar agente virt
  import_playbook: "config_agent_virt.yml"

- name: Configurar SELinux
  import_playbook: "config_selinux.yml"

- name: Configurar Cockpit
  import_playbook: "config_cockpit.yml"

- name: Configurar Red Hat Insights
  import_playbook: "config_redhat_insights.yml"

- name: Configurar Chrony
  import_playbook: "config-chrony.yml"

- name: Configurar parâmetros de kernel
  import_playbook: "config_kernel_parameters.yml"

- name: Configurar usuários de serviço
  import_playbook: "config_service_users.yml"

- name: Configurar node exporter
  import_playbook: "config_node_exporter.yml"

#  - name: Configurar Promtail
#    import_playbook: "promtail_agent.yml"

- name: test env var
  import_playbook: "env_ansible.yml"
