---
- name: Automate SNOW - Incident Closed
  hosts: localhost
  connection: local
  vars_files:
    - vars/main.yml
  collections:
    - servicenow.itsm

  tasks:
    # Always give your tasks a useful name
      # This task leverages the 'incident' module from the 'itsm' collection 
      # within the 'servicenow' namespace
    - name: Closed incident
      servicenow.itsm.incident:
        instance:
          host: "{{ sn_host }}"
          username: "{{ sn_username }}"
          password: "{{ sn_password }}"
        state: closed
        close_code: "Solved (Permanently)"
        close_notes: "This incident has been resolved through automated means via Ansible, and as a result, the ticket will now be marked as closed."
        number: "{{ sn_incident_number }}"