galaxy_info:
  author: Allan Roque
  description: Role para configurar e validar Apache com firewall
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - 8
        - 9

dependencies: []
