---
- name: Service Management Automation
  hosts: all
  gather_facts: false
  vars:
    service_name: "nginx"  # Enter the service name
    service_state: "started"  # Enter the desired state (started, stopped, restarted, reloaded)

  tasks:
    - name: Manage the service state
      ansible.builtin.service:
        name: "{{ service_name }}"
        state: "{{ service_state }}"
      become: true

    - name: Gather service facts
      ansible.builtin.service_facts:

    - name: Show the service status
      debug:
        msg: "The service {{ service_name }} is currently {{ ansible_facts.services[service_name + '.service'].state }}"
      when: service_name + '.service' in ansible_facts.services
