---
- name: Install and configure Gitea in Podman container
  hosts: hyper01.aroque.com.br
  gather_facts: false
  become: true
  tasks:

    - name: Start Gitea container with Podman Compose
      ansible.builtin.command: podman-compose -f /opt/gitea/podman-compose.yml up -d
      args:
        chdir: /opt/gitea