---
- name: Install and configure Gitea in Podman container
  hosts: hyper01.aroque.com.br
  gather_facts: false
  become: true
  tasks:
    - name: Create Gitea configuration directory
      ansible.builtin.file:
        path: /opt/gitea
        state: directory
        owner: 1000
        group: 1000
        mode: '0755'

    - name: Create Gitea data directory
      ansible.builtin.file:
        path: /opt/gitea/data
        state: directory
        owner: 1000
        group: 1000
        mode: '0755'

    - name: Create Gitea custom configuration directory
      ansible.builtin.file:
        path: /opt/gitea/custom
        state: directory
        owner: 1000
        group: 1000
        mode: '0755'

    - name: Create Gitea log directory
      ansible.builtin.file:
        path: /opt/gitea/log
        state: directory
        owner: 1000
        group: 1000
        mode: '0755'
        
    - name: Start Gitea container with Podman Compose
      ansible.builtin.command: podman-compose -f /opt/gitea/podman-compose.yml up -d
      args:
        chdir: /opt/gitea