---
- name: Install and configure Gitea in Podman container
  hosts: hyper01.aroque.com.br
  gather_facts: false
  become: true
  tasks:

    - name: Create git user
      ansible.builtin.user:
        name: git
        system: yes
        shell: /bin/bash
        comment: 'Git Version Control'
        home: /opt/gitea

    - name: Create Gitea configuration directory
      ansible.builtin.file:
        path: /opt/gitea
        state: directory
        owner: git
        group: git

    - name: Create Gitea data directory
      ansible.builtin.file:
        path: /opt/gitea/gitea
        state: directory
        owner: git
        group: git

    - name: Get UID of git user
      ansible.builtin.command: id -u git
      register: git_uid

    - name: Get GID of git group
      ansible.builtin.command: id -g git
      register: git_gid

    - name: Create SSH directory for git
      ansible.builtin.file:
        path: /home/git/.ssh
        state: directory
        owner: git
        group: git
        mode: '0700'

    - name: Set permissions for /opt/gitea
      ansible.builtin.command: chown -R git:git /opt/gitea
      become: true

    - name: Create Podman Compose file for Gitea
      ansible.builtin.copy:
        dest: /opt/gitea/podman-compose.yml
        content: |
          version: "3"

          networks:
            gitea:
              external: false

          services:
            server:
              image: docker.io/gitea/gitea:1.16.5
              container_name: gitea
              environment:
                - USER_UID={{ git_uid.stdout }}
                - USER_GID={{ git_gid.stdout }}
              restart: always
              networks:
                - gitea
              volumes:
                - /opt/gitea/gitea:/data
                - /home/git/.ssh:/data/git/.ssh
                - /etc/timezone:/etc/timezone:ro
                - /etc/localtime:/etc/localtime:ro
              ports:
                - "3000:3000"
                - "2222:22"

    - name: Start Gitea container with Podman Compose
      ansible.builtin.command: podman-compose -f /opt/gitea/podman-compose.yml up -d
      args:
        chdir: /opt/gitea