---
- name: Execução genérica de roles via AAP
  hosts: all
  gather_facts: false 

  tasks:
    - name: DEBUG - Mostrar role_name e variáveis resolvidas
      debug:
        msg:
          - "Role: {{ role_name }}"
          - "Variáveis:"
          - "{{ role_vars }}"
