---
- name: Executar role dinamicamente com variáveis do survey
  hosts: all
  gather_facts: false
  become: true

  vars:

  tasks:
    - name: Executar role dinamicamente
      include_role:
        name: "{{ role_name }}"