---
- name: Executar role dinamicamente com vari치veis do survey
  hosts: all
  gather_facts: false
  become: true

  vars:
    role_name: redhat.rhel_system_roles.selinux
    role_vars: |
      selinux_state: enforcing
      selinux_policy: targeted
#    role_name: "{{ role_name1 | default('') }}"
    role_vars_yaml: "{{ role_vars | default('{}') }}"
    parsed_vars: "{{ role_vars_yaml | from_yaml }}"

  pre_tasks:

    - name: Converter role_vars YAML para dicion치rio real
      set_fact:
        role_vars_dict: "{{ role_vars | from_yaml }}"

    - name: DEBUG - Verificar role e vari치veis resolvidas
      debug:
        msg:
          - "Role: {{ role_name }}"
          - "role_vars_yaml: {{ role_vars_yaml }}"
          - "role_vars_yaml: {{ role_vars_yaml | type_debug }}"          
          - "parsed_vars: {{ parsed_vars }}"
          - "parsed_vars type: {{ parsed_vars | type_debug }}"
          - "parsed_vars: {{ role_vars_dict }}"
          - "parsed_vars type: {{ role_vars_dict | type_debug }}"

    - name: Exportar vari치veis para painel do AAP (set_stats)
      set_stats:
        data:
          debug_role_name: "{{ role_name }}"
          debug_role_vars_yaml: "{{ role_vars_yaml }}"
          debug_role_vars_yaml_type: "{{ role_vars_yaml | type_debug }}"
          debug_parsed_vars: "{{ parsed_vars }}"
          debug_parsed_vars_type: "{{ parsed_vars | type_debug }}"
          debug_role_vars_dict: "{{ role_vars_dict }}"
          debug_role_vars_dict_type: "{{ role_vars_dict | type_debug }}"

  
  tasks:
    - name: Executar role dinamicamente
      include_role:
        name: "{{ role_name }}"
#      vars: parsed_vars
