---
- name: Teste com parsing dinâmico de role_vars
  hosts: all
  gather_facts: false
  become: true

  vars:
    # Simula o input do survey
    role_name: linux-system-roles.timesync
    role_vars: |-
      timesync_ntp_servers:
        - hostname: a.ntp.br
          iburst: true
        - hostname: b.ntp.br
          iburst: true
        - hostname: c.ntp.br
          iburst: true

  pre_tasks:
    - name: Validar e transformar role_vars em dicionário
      set_fact:
        resolved_role_vars: "{{ role_vars | from_yaml }}"

    - name: Expor cada variável do dicionário como variável normal
      set_fact: "{{ resolved_role_vars }}"

  tasks:
    - name: DEBUG - Mostrar role e variáveis
      debug:
        msg:
          - "Executando role: {{ role_name }}"
          - "Variáveis resolvidas: {{ resolved_role_vars }}"

    - name: Executar a role diretamente (sem vars:)
      include_role:
        name: "{{ role_name }}"
