---
- name: Configurar SELinux com role oficial
  hosts: all
  become: true
  gather_facts: false

  roles:
    - role: redhat.rhel_system_roles.selinux
      vars:
        selinux_state: enforcing
        selinux_policy: targeted
