---
- name: Teste simulado com entrada do tipo survey
  hosts: all
  gather_facts: false
  become: true

  vars:
    role_name: linux-system-roles.timesync
    role_vars: |-
      timesync_ntp_servers:
        - hostname: a.ntp.br
          iburst: true
        - hostname: b.ntp.br
          iburst: true
        - hostname: c.ntp.br
          iburst: true

  pre_tasks:
    - name: Validar e transformar role_vars em dicionário
      set_fact:
        resolved_role_vars: "{{ role_vars | from_yaml }}"

  tasks:
    - name: DEBUG - Mostrar variáveis
      debug:
        msg:
          - "Role: {{ role_name }}"
          - "Vars resolvidas:"
          - "{{ resolved_role_vars }}"

    - name: Injetar variáveis dinamicamente para execução da role
      set_fact:
        timesync_vars: "{{ resolved_role_vars }}"

    - name: Executar role usando vars preparadas
      include_role:
        name: "{{ role_name }}"
      vars: "{{ timesync_vars }}"
