---
- name: Executar role dinamicamente com variáveis do survey
  hosts: all
  gather_facts: false
  become: true

  vars:
    role_name: "{{ role_name | default('') }}"
    role_vars_yaml: "{{ role_vars | default('{}') }}"
    parsed_vars: "{{ role_vars_yaml | from_yaml }}"

  pre_tasks:
    - name: Validar que role_vars é YAML válido (dicionário)
      assert:
        that:
          - parsed_vars is mapping
        fail_msg: "Erro: role_vars precisa ser YAML válido no formato de dicionário"
        success_msg: "YAML validado com sucesso"

    - name: DEBUG - Verificar role e variáveis resolvidas
      debug:
        msg:
          - "Role: {{ role_name }}"
          - "role_vars_yaml: {{ role_vars_yaml }}"
          - "parsed_vars: {{ parsed_vars }}"
          - "parsed_vars type: {{ parsed_vars | type_debug }}"

  tasks:
    - name: Executar role dinamicamente
      include_role:
        name: "{{ role_name }}"
#      vars: "{{ parsed_vars }}"
