---
- name: Get IP address
  hosts: localhost
  gather_facts: false
  vars:
    host_name: "server01"
    host_domain: "aroque.com.br"
    host_fqdn: "{{ host_name }}.{{ host_domain }}"
    host_ip: ""
    host_type: "VIP"
    host_description: "Configured by Ansible"
    net_prefix: "192.168.100.0"
    net_cidr: "24"
  tasks:
    - name: Acquire next available IP address on {{ net_prefix }}/{{ net_cidr }} network
      netbox.netbox.netbox_ip_address:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          prefix: "{{ net_prefix }}/{{ net_cidr }}"
          dns_name: "{{ host_fqdn }}"
          description: "{{ host_description }}"
          role: "{{ host_type }}"
          status: "active"
        state: "new"
        validate_certs: no
      register: host_ip_output

    - name: Debug host_ip_output value
      debug:
        var: host_ip_output

    - name: Updating the value of the variable host_ip
      set_fact:
        host_ip: "{{ host_ip_output.ip_address.address.split('/')[0] }}"

    - name: Set host IP address variable
      set_stats:
        data:
          host_ip: "{{ host_ip_output.ip_address.address.split('/')[0] }}"

    - name: Set Job ID number
      set_stats:
        data:
          ac_job_id: "{{ awx_job_id }}"