---
- name: Configure basic IPAM in NetBox
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create site
      netbox.netbox.netbox_site:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: "Lab"
          slug: "lab"
        state: present

    - name: Create tenant
      netbox.netbox.netbox_tenant:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: "MyTenant"
          slug: "mytenant"
        state: present

    - name: Create device role
      netbox.netbox.netbox_device_role:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: "Server"
          slug: "server"
          color: "ff0000"
        state: present

    - name: Create platform
      netbox.netbox.netbox_platform:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: "KVM"
          slug: "kvm"
        state: present