---
- name: Start NetBox with Podman
  hosts: hyper01.aroque.com.br
  become: true
  tasks:
    - name: Create podman-compose.override.yml
      ansible.builtin.copy:
        dest: /opt/netbox-docker/docker-compose.override.yml
        content: |
          version: '3.4'
          services:
            netbox:
              ports:
              - 8000:8080

    - name: Pull and start NetBox containers with Podman Compose
      ansible.builtin.command: podman-compose up -d
      args:
        chdir: /opt/netbox-docker

    - name: Wait for NetBox to be healthy
      ansible.builtin.wait_for:
        port: 8000
        delay: 30
        timeout: 300
