---
- name: Deploy NetBox with Podman
  hosts: hyper01.aroque.com.br
  tasks:

    - name: Create NetBox config directory
      file:
        path: "/opt/netbox/config"
        state: directory
        owner: "1000"
        group: "1000"

    - name: Run NetBox container
      containers.podman.podman_container:
        name: netbox
        image: lscr.io/linuxserver/netbox:latest
        state: started
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: "Etc/UTC"
          SUPERUSER_EMAIL: "admin@example.com"
          SUPERUSER_PASSWORD: "redhat"
          ALLOWED_HOST: "localhost,127.0.0.1"
          DB_NAME: "netbox"
          DB_USER: "netbox"
          DB_PASSWORD: "redhat"
          DB_HOST: "localhost"
          DB_PORT: "5432"
          REDIS_HOST: "localhost"
          REDIS_PORT: "6379"
          REDIS_DB_TASK: "0"
          REDIS_DB_CACHE: "1"
        ports:
          - "8000:8000"
        volumes:
          - "/opt/config:/config"
        restart_policy: unless-stopped
