---
- name: Deploy NetBox with Podman
  hosts: hyper01.aroque.com.br
  become: true
  tasks:
    - name: Ensure Podman is installed
      package:
        name: podman
        state: present

    - name: Ensure Git is installed
      package:
        name: git
        state: present

    - name: Create NetBox config directory
      file:
        path: "/opt/netbox/"
        state: directory
        owner: "1000"
        group: "1000"
        mode: '0755'

    - name: Ensure correct permissions on the config directory
      command: chown -R 1000:1000 /opt/netbox/

    - name: Run NetBox container
      containers.podman.podman_container:
        name: netbox
        image: lscr.io/linuxserver/netbox:latest
        state: started
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: "America/Sao_Paulo"
          SUPERUSER_EMAIL: "admin@example.com"
          SUPERUSER_PASSWORD: "redhat"
          ALLOWED_HOST: "localhost,127.0.0.1"
          DB_NAME: "netbox"
          DB_USER: "netbox"
          DB_PASSWORD: "redhat"
          DB_HOST: "localhost"
          DB_PORT: "5432"
          REDIS_HOST: "localhost"
          REDIS_PORT: "6379"
          REDIS_DB_TASK: "0"
          REDIS_DB_CACHE: "1"
        ports:
          - "8000:8000"
        volumes:
          - "/opt/netbox/:/config"
        restart_policy: unless-stopped
