---
- name: Deploy NetBox with Docker
  hosts: hyper01.aroque.com.br
  become: true
  tasks:

    - name: Clone NetBox Docker repository
      ansible.builtin.git:
        repo: 'https://github.com/netbox-community/netbox-docker.git'
        dest: /opt/netbox-docker

    - name: Create docker-compose.override.yml
      ansible.builtin.copy:
        dest: /opt/netbox-docker/docker-compose.override.yml
        content: |
          version: '3.4'
          services:
            netbox:
              ports:
              - 8000:8080

    - name: Pull and start NetBox containers with Podman Compose
      ansible.builtin.command: podman-compose up -d
      args:
        chdir: /opt/netbox-docker

    - name: Wait for NetBox to be healthy
      ansible.builtin.wait_for:
        path: "http://localhost:8000"
        port: 8000
        delay: 30
        timeout: 300

#    - name: Create NetBox admin user
#      ansible.builtin.command:
#        cmd: podman-compose exec netbox /opt/netbox/netbox/manage.py createsuperuser
#        args:
#          chdir: /opt/netbox-docker
