---
- name: Deploy NetBox with Podman
  hosts: hyper01.aroque.com.br
  tasks:

    - name: Modify docker-compose.yml for Podman compatibility
      replace:
        path: /opt/netbox-docker/docker-compose.yml
        regexp: 'image:'
        replace: 'image: docker.io/'

    - name: Create docker-compose.override.yml to set the port
      copy:
        dest: /opt/netbox-docker/docker-compose.override.yml
        content: |
          version: '3.4'
          services:
            netbox:
              ports:
                - 8000:8080

    - name: Pull NetBox Docker containers
      command: podman-compose -f /opt/netbox-docker/docker-compose.yml pull
      args:
        chdir: /opt/netbox-docker

    - name: Run NetBox with Podman
      command: podman-compose -f /opt/netbox-docker/docker-compose.yml up -d
      args:
        chdir: /opt/netbox-docker

    - name: Wait for NetBox to be healthy
      wait_for:
        path: "http://localhost:8000"
        port: 8000
        delay: 30
        timeout: 300

    - name: Create NetBox admin user
      command: podman-compose -f /opt/netbox-docker/docker-compose.yml exec netbox /opt/netbox/netbox/manage.py createsuperuser
      args:
        chdir: /opt/netbox-docker