---
- name: Capture alertmanager alerts
  hosts: localhost
  sources:
    - ansible.eda.alertmanager:
        host: 0.0.0.0
        port: 5050
        data_alerts_path: alerts
        data_host_path: labels.instance
        data_path_separator: .
        skip_original_data: true

  rules:
#################
# Instance Down #
#################
    - name: Instance Down
      condition: >
        event.alert.labels.alertname == "InstanceDown" and
        event.alert.status == "firing" and
        (event.meta.hosts == "web01.aroque.com.br" or event.meta.hosts == "web2.aroque.com.br")
      action:
        run_workflow_template:
          name: SH High Memory Usage
          organization: Default
          job_args:
            limit: "{{ event.meta.hosts }}"

###########
# SELinux #
###########

    - name: SELinux was disabled
      condition: event.alert.labels.alertname == "SELinuxDisabled" and event.alert.status == "firing"
      action:
        run_workflow_template:
          name: WF SH SELinux Settings
          organization: Default
          job_args:
            limit: "{{ event.meta.hosts }}"
          post_events: true

    - name: SELinux was enabled
      condition: event.alert.labels.alertname == "SELinuxDisabled" and event.alert.status == "resolved"
      action:
        debug:
          msg: "enabled on: {{ event.meta.hosts }}"

##############
# FileSystem #
##############

    - name: High Filesystem Usage
      condition: event.alert.labels.alertname == "HighFilesystemUsage" and event.alert.status == "firing"
      action:
        run_workflow_template:
          name: WF SH Filesystem High Usage
          organization: Default
          job_args:
            limit: "{{ event.meta.hosts }}"

##########
# Memory #
##########
    - name: High Memory Usage
      condition: event.alert.labels.alertname == "HighMemoryUsage" and event.alert.status == "firing"
      action:
        run_job_template:
          name: SH High Memory Usage
          organization: Default
          job_args:
            limit: "{{ event.meta.hosts }}"

    - name: Low Memory Usage
      condition: event.alert.labels.alertname == "HighMemoryUsage" and event.alert.status == "resolved"
      action:
        run_job_template:
          name: SH Low Memory Usage
          organization: Default
          job_args:
            limit: "{{ event.meta.hosts }}"

##############
# ALL events #
##############
    - name: Capture all other events from this source
      condition: event.alert is defined
      action:
        debug:

###############
# HTTP APACHE #
################

    - name: Respond to HTTP Service Down Alert
      condition: event.alert.labels.job == "http" and event.alert.status == "firing"
      action:
        run_job_template:
          name: SH HTTP Service Down
          organization: Default
          job_args:
            limit: "{{ event.meta.hosts }}"
