---
- name: Capture all journald logs
  hosts: localhost
  sources:
    - ansible.eda.journald:
        match: "ALL"

  rules:
    - name: Print and Debug Journald Events
      condition: event.journald is defined
      actions:
        debug:

#        - print_event:
#            pretty: true
#            var_root: event.journald.message
#        - debug:
#            msg: "enabled on: {{ event.meta.hosts }}"
