---
- name: Listen for events on a webhook
  hosts: all
  ## Define our source for events
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  ## Define the conditions we are looking for
  rules:
    - name: Debug all received events
      condition: event.payload is defined  # Condição para verificar se existe algum dado no payload
      action:
        debug:
          msg: "Received data: {{ event.payload }}"