---
- name: Capture alertmanager alerts
  hosts: localhost
  sources:
    - ansible.eda.alertmanager:
        host: 0.0.0.0
        port: 5054
        data_alerts_path: alerts
        data_host_path: labels.instance
        data_path_separator: .
        skip_original_data: true

  rules:
    - name: High Memory Usage
      condition: event.alert.labels.alertname == "HighMemoryUsage" and event.alert.status == "firing"
      action:
        run_job_template:
          name: SH High Memory Usage
          organization: Default
          job_args:
            limit: "{{ event.meta.hosts }}"

    - name: Low Memory Usage
      condition: event.alert.labels.alertname == "HighMemoryUsage" and event.alert.status == "resolved"
      action:
        run_job_template:
          name: SH Low Memory Usage
          organization: Default
          job_args:
            limit: "{{ event.meta.hosts }}"
