---
- name: Create directory for Alertmanager configuration
  file:
    path: /opt/alertmanager
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copy Alertmanager configuration file
  copy:
    src: alertmanager.yml
    dest: /opt/alertmanager/alertmanager.yml

- name: Run Alertmanager container
  containers.podman.podman_container:
    name: alertmanager
    image: docker.io/prom/alertmanager
    state: started
    ports:
      - "9093:9093"
    volumes:
      - /opt/alertmanager/alertmanager.yml:/etc/alertmanager/config.yml
