---
- name: Create directory for Blackbox Exporter configuration
  file:
    path: /opt/blackbox_exporter
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Create Blackbox Exporter configuration file
  copy:
    src: files/blackbox.yml
    dest: /opt/blackbox_exporter/blackbox.yml

- name: Run Blackbox Exporter container
  containers.podman.podman_container:
    name: blackbox_exporter
    image: docker.io/prom/blackbox-exporter
    state: started
    ports:
      - "9115:9115"
    volumes:
      - /opt/blackbox_exporter/blackbox.yml:/etc/blackbox_exporter/config.yml
    dns_servers:
      - 192.168.100.10
      - 8.8.8.8
  register: blackbox_exporter_result