---
- name: Setup Prometheus, Alertmanager, and Blackbox Exporter with Podman
  hosts: hyper01.aroque.com.br
  become: yes

  tasks:
    - name: Include Prometheus Playbook
      include_playbook: prometheus.yml

    - name: Include Alertmanager Playbook
      include_playbook: alertmanager.yml

    - name: Include Blackbox Exporter Playbook
      include_playbook: blackbox_exporter.yml

