---
- name: Setup Prometheus, Alertmanager, and Blackbox Exporter with Podman
  hosts: hyper01.aroque.com.br
  become: yes

  tasks:
    - name: Include Prometheus Playbook
      import_playbook: prometheus.yml

    - name: Include Alertmanager Playbook
      import_playbook: alertmanager.yml

    - name: Include Blackbox Exporter Playbook
      import_playbook: blackbox_exporter.yml

