---
- name: Create directory for Prometheus configuration
  file:
    path: /opt/prometheus
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: List hosts in infra group
  debug:
    msg: "{{ item }}"
  loop: "{{ groups['INFRA'] }}"

- name: Create Prometheus configuration file
  template:
   src: prometheus.yml.j2
   dest: /etc/prometheus/prometheus.yml

- name: Run Prometheus container
  podman_container:
    name: prometheus
    image: prom/prometheus
    state: started
    ports:
      - "9090:9090"
    volumes:
      - /opt/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
