---
- name: Create directory for Prometheus configuration
  file:
    path: /opt/prometheus
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: List hosts in infra group
  debug:
    msg: "{{ item }}"
  loop: "{{ groups['INFRA'] }}"

- name: Create Prometheus configuration file
  template:
   src: prometheus.yml.j2
   dest: /opt/prometheus/prometheus.yml

- name: Copy alertmanager files
  copy:
    src: "{{ item }}"
    dest: /opt/prometheus/"
  loop:
    - alert_selinux_disabled.yml
    - alert_filesystem_usage.yml
    - alert_memory_usage.yml
    - alert_instance_availability.yml
    - alert_http.yml

- name: Run Prometheus container
  containers.podman.podman_container:
    name: prometheus
    image: docker.io/prom/prometheus
    state: started
    ports:
      - "9090:9090"
    volumes:
      - /opt/prometheus/:/etc/prometheus/
