---
- name: Restart Prometheus, Alertmanager, and Blackbox Exporter containers
  hosts: hyper01.aroque.com.br
  become: yes
  tasks:
    - name: Stop and remove Blackbox Exporter container
      containers.podman.podman_container:
        name: blackbox_exporter
        state: absent

    - name: Stop and remove Alertmanager container
      containers.podman.podman_container:
        name: alertmanager
        state: absent

    - name: Stop and remove Prometheus container
      containers.podman.podman_container:
        name: prometheus
        state: absent